const { Op } = require("sequelize");
const { KategoriLembur, JenisPekerjaanLembur, Spkl, Lembur } = require("../../models");
const AppError = require("../../utils/appError");
const privileged = (user) => user?.is_super_admin === "Y" || ["SUPER_ADMIN", "ADMIN"].includes(String(user?.kode_role || "").toUpperCase());

class MasterLemburService {
    assertWrite(user) { if (!privileged(user)) throw new AppError("Hanya Super Admin dan Administrator yang dapat mengubah Master Lembur", 403); }
    async list(filters = {}) {
        const where = filters.is_active ? { is_active: filters.is_active } : {};
        return KategoriLembur.findAll({ where, include: [{ model: JenisPekerjaanLembur, as: "jenisPekerjaan", required: false, where: filters.is_active ? { is_active: filters.is_active } : undefined }], order: [["urutan", "ASC"], ["nama_kategori", "ASC"], [{ model: JenisPekerjaanLembur, as: "jenisPekerjaan" }, "urutan", "ASC"]] });
    }
    async createCategory(data, user) { this.assertWrite(user); return KategoriLembur.create({ ...data, kode_kategori: data.kode_kategori.toUpperCase(), created_by: user.id_user }); }
    async updateCategory(id, data, user) { this.assertWrite(user); const row = await KategoriLembur.findByPk(id); if (!row) throw new AppError("Kategori lembur tidak ditemukan", 404); if (data.jenis_mode === "NONE") { const count = await JenisPekerjaanLembur.count({ where: { id_kategori_lembur: id, is_active: "Y" } }); if (count) throw new AppError("Nonaktifkan atau hapus seluruh jenis pekerjaan sebelum mengubah mode menjadi NONE", 409); } await row.update({ ...data, kode_kategori: data.kode_kategori.toUpperCase(), updated_by: user.id_user }); return row; }
    async deleteCategory(id, user) { this.assertWrite(user); const used = await Promise.all([JenisPekerjaanLembur.count({ where: { id_kategori_lembur: id } }), Spkl.count({ where: { id_kategori_lembur: id } }), Lembur.count({ where: { id_kategori_lembur: id } })]); if (used.some(Boolean)) throw new AppError("Kategori sudah digunakan dan tidak dapat dihapus; nonaktifkan kategori sebagai gantinya", 409); const deleted = await KategoriLembur.destroy({ where: { id_kategori_lembur: id } }); if (!deleted) throw new AppError("Kategori lembur tidak ditemukan", 404); }
    async createType(data, user) { this.assertWrite(user); const category = await KategoriLembur.findByPk(data.id_kategori_lembur); if (!category) throw new AppError("Kategori lembur tidak ditemukan", 404); if (category.jenis_mode === "NONE") throw new AppError("Kategori dengan mode NONE tidak dapat memiliki jenis pekerjaan", 422); return JenisPekerjaanLembur.create({ ...data, kode_jenis: data.kode_jenis.toUpperCase(), created_by: user.id_user }); }
    async updateType(id, data, user) { this.assertWrite(user); const row = await JenisPekerjaanLembur.findByPk(id); if (!row) throw new AppError("Jenis pekerjaan lembur tidak ditemukan", 404); const category = await KategoriLembur.findByPk(data.id_kategori_lembur); if (!category || category.jenis_mode === "NONE") throw new AppError("Kategori tujuan tidak valid untuk jenis pekerjaan", 422); await row.update({ ...data, kode_jenis: data.kode_jenis.toUpperCase(), updated_by: user.id_user }); return row; }
    async deleteType(id, user) { this.assertWrite(user); const used = await Promise.all([Spkl.count({ where: { id_jenis_pekerjaan_lembur: id } }), Lembur.count({ where: { id_jenis_pekerjaan_lembur: id } })]); if (used.some(Boolean)) throw new AppError("Jenis pekerjaan sudah digunakan dan tidak dapat dihapus; nonaktifkan sebagai gantinya", 409); const deleted = await JenisPekerjaanLembur.destroy({ where: { id_jenis_pekerjaan_lembur: id } }); if (!deleted) throw new AppError("Jenis pekerjaan lembur tidak ditemukan", 404); }
    async resolve(idCategory, idType, activeOnly = true) { const category = await KategoriLembur.findByPk(idCategory); if (!category || (activeOnly && category.is_active !== "Y")) throw new AppError("Kategori lembur tidak valid atau tidak aktif", 422); let type = null; if (idType) { type = await JenisPekerjaanLembur.findOne({ where: { id_jenis_pekerjaan_lembur: idType, id_kategori_lembur: idCategory, ...(activeOnly ? { is_active: "Y" } : {}) } }); if (!type) throw new AppError("Jenis pekerjaan tidak sesuai dengan kategori lembur", 422); } if (category.jenis_mode === "REQUIRED" && !type) throw new AppError("Jenis pekerjaan wajib dipilih untuk kategori ini", 422); if (category.jenis_mode === "NONE" && type) throw new AppError("Kategori ini tidak menggunakan jenis pekerjaan", 422); return { category, type }; }
}
module.exports = new MasterLemburService();
